//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetoshkinFloor
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;
    using System.Xml.Schema;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnerMinCostHistory = new HashSet<PartnerMinCostHistory>();
            this.PartnerProduct = new HashSet<PartnerProduct>();
            this.PointSales = new HashSet<PointSales>();
        }
    
        public int PartnerID { get; set; }
        public string OrganizationTypeName { get; set; }
        public int PartnerType { get; set; }
        public string PartnerCompanyName { get; set; }
        public string PartnerDirectorSurname { get; set; }
        public string PartnerDirectorName { get; set; }
        public string PartnerDirectorPatronymic { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerPhoneNumber { get; set; }
        public int PartnerCompanyAdressIndex { get; set; }
        public string PartnerCompanyAdressRegion { get; set; }
        public string PartnerCompanyAdressCity { get; set; }
        public string PartnerCompanyAdressStreet { get; set; }
        public string PartnerCompanyAdressHouse { get; set; }
        public string PartnerCompanyINN { get; set; }
        public double PartnerRating { get; set; }
        public byte[] PartnerLogo { get; set; }
    
        public virtual OrganizationForm OrganizationForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerMinCostHistory> PartnerMinCostHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointSales> PointSales { get; set; }

        public string PartnerTypeString
        {
            get
            {
                return OrganizationForm.OrganizationTypeName;
            }
        }
    }
}
