//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetoshkinFloor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VetoshkinFloorMasterEntities : DbContext
    {
        private static VetoshkinFloorMasterEntities _context;

        public static VetoshkinFloorMasterEntities GetContext()
        {
            if (_context == null)
                _context = new VetoshkinFloorMasterEntities();
            return _context;
        }

        public VetoshkinFloorMasterEntities()
            : base("name=VetoshkinFloorMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialsCount> MaterialsCount { get; set; }
        public virtual DbSet<MaterialsType> MaterialsType { get; set; }
        public virtual DbSet<MeasurementUnits> MeasurementUnits { get; set; }
        public virtual DbSet<OrganizationForm> OrganizationForm { get; set; }
        public virtual DbSet<PartnerMinCostHistory> PartnerMinCostHistory { get; set; }
        public virtual DbSet<PartnerProduct> PartnerProduct { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<PointSales> PointSales { get; set; }
        public virtual DbSet<ProductCount> ProductCount { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<SupplierType> SupplierType { get; set; }
        public virtual DbSet<SupplyHistory> SupplyHistory { get; set; }
    }
}
